version: "3.8"  # optional since v1.27.0
services:
  node:
    container_name: "app"
    build: .
    environment:
      - NODE_ENV=PRD
      - PORT=3000
    volumes:
      - ./:/home/node/app
    depends_on:
      - postgresqls
    ports:
      - "3000:3000"
    networks:
      - default  
    command: "yarn start"

  postgresqls:
    container_name: "postgresqlpostgis"
    image: "postgis/postgis"
    ports: 
      - "5433:5432"
    volumes:
       - db_persdata:/var/lib/postgrespers
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: teste
    networks:
      - default
networks:
  default:
volumes:
  db_persdata : {}